### ISSUE TITLE
don't use JDK

### ISSUE THREAD

**Issue by jeanpommier** [Kharatsa/odkaggregate#3]
Hi,
There is a way to _not use_ JDK in the run.sh script. jar and war are just zip files, so you can use zip instead, it's way lighter. 
You'll find a sample adapted run.sh file in [my repository](https://raw.githubusercontent.com/jeanpommier/docker-padre1/master/odkaggregate/run.sh).
And thanks for this nice job, that gave me a good quickstart.

**Comment by seanjh** [comment]
I had no idea you could extract a jar with `unzip`. Thanks for spotting that! I'll try to make time to incorporate this change ASAP.

**Comment by jeanpommier** [comment]
Hi,

Glad I helped you learn something new. That's something I found quite a 
while ago : a war file can simply be unzippped and copied, instead of 
relying on tomcat to deploy it.

You can just look at how I did it in my run.sh file. I've not changed 
much, it will not need much to incorporate the change. I've already 
tested it, it works like a charm !

I'm the one who should thank you, you made me spare more time than the 
opposite. It's just basic constructive feedback.

Cheers,


Jean

*Jean Pommier -- pi-Geosolutions*

Ingénieur, consultant indépendant

Tél. : (+33) 6 09 23 21 36
E-mail : jp@pi-geosolutions.fr
Web : www.pi-geosolutions.fr
